// Keywords & Definitions
var keywords = {
	"50/50S" : "A type of mix-up where a player must guess between two options.",
	"50/50" : "A type of mix-up where a player must guess between two options.",
	"ACTIVE" : "The amount of frames a move has in which it can connect with an opponent.",
	"AIR-TO-AIRING" : "An aerial attack that is done against an opponent who is in the air.",
	"AIR-TO-AIRED" : "An aerial attack that is done against an opponent who is in the air.",
	"AIR-TO-AIRS" : "An aerial attack that is done against an opponent who is in the air.",
	"AIR-TO-AIR" : "An aerial attack that is done against an opponent who is in the air.",
	"ANTI-AIRING" : "A grounded attack that is done against an opponent who is in the air.",
	"ANTI-AIRED" : "A grounded attack that is done against an opponent who is in the air.",
	"ANTI-AIRS" : "A grounded attack that is done against an opponent who is in the air.",
	"ANTI-AIR" : "A grounded attack that is done against an opponent who is in the air.",
	// "ARMOR BREAK" : "The ability to destroy a character's armor.",
	// "ARMOR" : "A state that prevents a character from flinching when being hit.",
	// "BACKDASHING" : "A type of movement in which a character is able to quickly move backward while covering a good amount of distance.",
	// "BACKDASHED" : "A type of movement in which a character is able to quickly move backward while covering a good amount of distance.",
	// "BACKDASHES" : "A type of movement in which a character is able to quickly move backward while covering a good amount of distance.",
	// "BACKDASH" : "A type of movement in which a character is able to quickly move backward while covering a good amount of distance.",
	"BAIT" : "To force a reaction out of the opponent and counter that reaction.",
	"BLOCK ADVANTAGE" : "The amount of frames a move gives after it is blocked.",
	"BLOCK STUN" : "The amount of frames a player is unable to move for while blocking an attack.",
	"BLOCKSTUN" : "The amount of frames a player is unable to move for while blocking an attack.",
	"BLOCKSTRINGS" : "A combination of single-hitting attacks that are done on block.",
	"BLOCKSTRING" : "A combination of single-hitting attacks that are done on block.",
	"BNB" : "Short for “Bread and Butter”. A combo that is both easy and efficient in terms of damage and consistency with a low chance of dropping.",
	"BUFFER" : "To preemptively enter in specific inputs of a move while another action is taking place so that the move comes out as early as possible.",
	"CANCEL ADVANTAGE" : "The amount of frames a move gives when cancelled into another move.",
	"CANCELLING" : "To exit out of a move by entering in certain inputs.",
	"CANCELLED" : "To exit out of a move by entering in certain inputs.",
	"CANCELS" : "To exit out of a move by entering in certain inputs.",
	"CANCEL" : "To exit out of a move by entering in certain inputs.",
	"CHIP DAMAGE" : "The amount of damage that is done when an attack is blocked.",
	"COMBO BREAKER" : "A defensive mechanic that allows a player to escape a combo.",
	"COMMAND GRAB" : "A special type of throw that cannot be throw teched.",
	"COUNTERZONE" : "To counter an opponent who is controlling space. Teleports are commonly used in counterzoning to avoid projectiles and approach the opponent.",
	"COUNTERZONING" : "A type of playstyle that relies on countering an opponent who is controlling space. Teleports are commonly used in counterzoning to avoid projectiles and approach the opponent.",
	"CROSS-UP" : "An attack that is done from behind which can alter the opponent's directions.",
	// "DASH" : "A type of movement in which a character is able to quickly move forward or backward while covering a good amount of distance.",
	"FOOTSIES" : "The concept of staying in and out of both player's attack range, baiting the opponent into committing an action, and punishing them for their mistakes.",
	"FOOTSIE" : "The concept of staying in and out of both player's attack range, baiting the opponent into committing an action, and punishing them for their mistakes.",
	// "FORWARD DASH" : "A type of movement in which a character is able to quickly move forward while covering a good amount of distance.",
	"FRAME ADVANTAGE" : "A situation where a player is able to move for a certain number of frames before the opponent.",
	"ADVANTAGEOUS" : "A situation where a player is able to move for a certain number of frames before the opponent.",
	"ADVANTAGE" : "A situation where a player is able to move for a certain number of frames before the opponent.",
	"FRAME DISADVANTAGE" : "A situation where the opponent is able to move a certain number of frames before a player.",
	"DISADVANTAGEOUS" : "A situation where the opponent is able to move a certain number of frames before a player.",
	"DISADVANTAGE" : "A situation where the opponent is able to move a certain number of frames before a player.",
	"FRAME TRAP" : "A situation where a player is at enough frame advantage to perform an follow-up attack which cannot be interrupted.",
	"FRAMETRAP" : "A situation where a player is at enough frame advantage to perform an follow-up attack which cannot be interrupted.",
	// "FRAMES" : "The standard unit of time in fighting games. One frame is equal to 1/60th of a second.",
	// "FRAME" : "The standard unit of time in fighting games. One frame is equal to 1/60th of a second.",
	"FUZZY GUARDING" : "A pattern of blocking that allows a player to defend against the opponent's attacks and mix-ups.",
	"FUZZY GUARDED" : "A pattern of blocking that allows a player to defend against the opponent's attacks and mix-ups.",
	"FUZZY GUARD" : "A pattern of blocking that allows a player to defend against the opponent's attacks and mix-ups.",
	"GRAPPLER" : "An archetype that focuses on grabbing the opponent, typically using a combination of normal attacks and command grabs for mix-ups.",
	"GUARD CANCEL" : "A defensive mechanic that allows a player to cancel out of block stun with another move to counterattack the opponent.",
	"HEALTHBAR" : "A gauge that measures a player's health. When a healthbar is depleted, that player loses.",
	// "HIGH ATTACKS" : "A type of attack that hits the upper area of the opponent. High attacks can be avoided by crouching.",
	// "HIGH ATTACK" : "A type of attack that hits the upper area of the opponent. High attacks can be avoided by crouching.",
	"HIT ADVANTAGE" : "The amount of frames a move gives after it hits.",
	"HIT CONFIRMING" : "The act of seeing an attack hitting the opponent and reacting with another attack.",
	"HIT CONFIRMED" : "The act of seeing an attack hitting the opponent and reacting with another attack.",
	"HIT CONFIRMABLE" : "The act of seeing an attack hitting the opponent and reacting with another attack.",
	"HIT CONFIRM" : "The act of seeing an attack hitting the opponent and reacting with another attack.",
	"HIT STUN" : "The amount of frames a player is unable to move for while being hit by an attack.",
	"HITSTUN" : "The amount of frames a player is unable to move for while being hit by an attack.",
	"HITBOXES" : "The area of an attack that can connect with the opponent.",
	"HITBOX" : "The area of an attack that can connect with the opponent.",
	"HURTBOXES" : "The area of a character that can be hit by an attack.",
	"HURTBOX" : "The area of a character that can be hit by an attack.",
	"INSTANT-AIR" : "To perform an action immediately after jumping.",
	"INVINCIBILITY" : "A state that prevents a character from flinching and taking any damage from the opponent.",
	"INVINCIBLE" : "A state that prevents a character from flinching and taking any damage from the opponent.",
	// "JABBING" : "A high attack that is typically fast on start-up and recovery.",
	// "JABS" : "A high attack that is typically fast on start-up and recovery.",
	// "JAB" : "A high attack that is typically fast on start-up and recovery.",
	"JAILS" : "A situation where a player is at enough frame advantage to connect another attack which cannot be avoided and must be blocked.",
	"JAIL" : "A situation where a player is at enough frame advantage to connect another attack which cannot be avoided and must be blocked.",
	// "LOW ATTACKS" : "A type of attack that hits the lower area of the opponent. Low attacks cannot be blocked by standing and must be blocked by crouching.",
	// "LOW ATTACK" : "A type of attack that hits the lower area of the opponent. Low attacks cannot be blocked by standing and must be blocked by crouching.",
	"LOW PROFILING" : "The ability to avoid certain attacks by lowering a character's hurtbox.",
	"LOW PROFILED" : "The ability to avoid certain attacks by lowering a character's hurtbox.",
	"LOW PROFILES" : "The ability to avoid certain attacks by lowering a character's hurtbox.",
	"LOW PROFILE" : "The ability to avoid certain attacks by lowering a character's hurtbox.",
	"MEATY" : "An attack that is done on the first frame of an opponent's wakeup after being knocked down.",
	// "METAGAME" : "Used to describe the most dominant or strongest way of playing the game.",
	// "META" : "Short for "metagame". Used to describe the most dominant or strongest way of playing the game.",
	// "MID ATTACKS" : "A type of attack that hits the middle area of the opponent. Mid attacks cannot be avoided by crouching.",
	// "MID ATTACK" : "A type of attack that hits the middle area of the opponent. Mid attacks cannot be avoided by crouching.",
	"MIX-UPS" : "A situation where a player must guess between two or more options.",
	"MIX-UP" : "A situation where a player must guess between two or more options.",
	"MIXUPS" : "A situation where a player must guess between two or more options.",
	"MIXUP" : "A situation where a player must guess between two or more options.",
	"NEUTRAL JUMP" : "A jump that is done directly upwards.",
	"NEUTRAL GAME" : "A situation where neither player has an advantage over the other.",
	"NEUTRAL" : "A situation where neither player has an advantage over the other.",
	"OKIZEME" : "The concept of attacking the opponent while they are knocked down.",
	"OPTION SELECTING" : "An advanced technique that covers multiple options and leaves the player in an advantageous situation regardless of the outcome.",
	"OPTION SELECTS" : "An advanced technique that covers multiple options and leaves the player in an advantageous situation regardless of the outcome.",
	"OPTION SELECT" : "An advanced technique that covers multiple options and leaves the player in an advantageous situation regardless of the outcome.",
	// "OVERHEAD ATTACKS" : "A type of attack that hits the middle area of the opponent. Overhead attacks cannot be blocked by crouching and must be blocked by standing.",
	// "OVERHEAD ATTACK" : "A type of attack that hits the middle area of the opponent. Overhead attacks cannot be blocked by crouching and must be blocked by standing.",
	"PARRYING" : "A defensive move that allows a player to counterattack the opponent. Parries are generally active longer than normal attacks, but consequently have higher recovery.",
	"PARRIED" : "A defensive move that allows a player to counterattack the opponent. Parries are generally active longer than normal attacks, but consequently have higher recovery.",
	"PARRIES" : "A defensive move that allows a player to counterattack the opponent. Parries are generally active longer than normal attacks, but consequently have higher recovery.",
	"PARRY" : "A defensive move that allows a player to counterattack the opponent. Parries are generally active longer than normal attacks, but consequently have higher recovery.",
	// "POKING" : "A normal attack that is typically fast on start-up and recovery, and is generally safe to throw out.",
	// "POKES" : "A normal attack that is typically fast on start-up and recovery, and is generally safe to throw out.",
	// "POKE" : "A normal attack that is typically fast on start-up and recovery, and is generally safe to throw out.",
	// "PRESSURE" : "The concept of using a series of attacks to keep the opponent on the defensive. Pressure typically consists of using staggers or moves that grant frame advantage.",
	// "PROJECTILES" : "A type of attack that is thrown at the opponent. Projectiles are typically used to attack from long distances while controlling space.",
	// "PROJECTILE" : "A type of attack that is thrown at the opponent. Projectiles are typically used to attack from long distances while controlling space.",
	// "PUNISHABLE" : "To attack an opponent who is recovering from performing a move and is unable to block in time.",
	// "PUNISHING" : "To attack an opponent who is recovering from performing a move and is unable to block in time.",
	// "PUNISHED" : "To attack an opponent who is recovering from performing a move and is unable to block in time.",
	// "PUNISHES" : "To attack an opponent who is recovering from performing a move and is unable to block in time.",
	// "PUNISH" : "To attack an opponent who is recovering from performing a move and is unable to block in time.",
	// "PUSH BLOCK" : "A defensive mechanic that allows a player to push the opponent away after blocking an attack.",
	// "REACTION" : "The ability to see an event and retaliate in time.",
	// "READING" : "The ability to predict the opponent's actions and movements based on their tendencies.",
	// "READS" : "The ability to predict the opponent's actions and movements based on their tendencies.",
	// "READ" : "The ability to predict the opponent's actions and movements based on their tendencies.",
	"RECOVERY" : "The amount of frames a move has after being used before the player is able to move again.",
	"RESTANDING" : "A situation where the opponent is left standing at the end of a combo.",
	"RESTANDS" : "A situation where the opponent is left standing at the end of a combo.",
	"RESTAND" : "A situation where the opponent is left standing at the end of a combo.",
	"RUSHDOWN" : "A type of playstyle that focuses on offense and aggressively attacking the opponent at close-range.",
	"SAFE JUMP" : "A technique that is done by jumping at the opponent after knocking them down and performing a jump attack while being able to recover in time to block their wakeup.",
	"SETPLAY" : "A type of playstyle that focuses on creating setups to continuously place the opponent in disadvantageous situations.",
	"SETUPS" : "The preparation of putting the opponent in a disadvantageous situation.",
	"SETUP" : "The preparation of putting the opponent in a disadvantageous situation.",
	"AUTO-SHIMMY" : "The act of baiting the opponent into releasing block by deluding them into thinking a throw is coming, then using an attack to hit the opponent.",
	"SHIMMY" : "The act of baiting the opponent into releasing block by deluding them into thinking a throw is coming, then using an attack to hit the opponent.",
	"START-UP" : "The amount of frames a move takes before becoming active.",
	// "STRINGS" : "A combination of single-hitting attacks.",
	// "STRING" : "A combination of single-hitting attacks.",
	"TECH ROLLING" : "The ability to roll away after being knocked down.",
	"TECH ROLLED" : "The ability to roll away after being knocked down.",
	"TECH ROLLS" : "The ability to roll away after being knocked down.",
	"TECH ROLL" : "The ability to roll away after being knocked down.",
	// "THROWING" : "An attack that is done to counter blocking. Throws are usually used to open opponents up who tend to block, but deal low damage and can be escaped by teching.",
	// "THROWS" : "An attack that is done to counter blocking. Throws are usually used to open opponents up who tend to block, but deal low damage and can be escaped by teching.",
	// "THROW" : "An attack that is done to counter blocking. Throws are usually used to open opponents up who tend to block, but deal low damage and can be escaped by teching.",
	"TECHED" : "The ability to escape a throw. Teching a throw is typically done by reacting to the throw and entering in a certain input within a short period of time.",
	"THROW TECH" : "The ability to escape a throw. Teching a throw is typically done by reacting to the throw and entering in a certain input within a short period of time.",
	"TRADES" : "A situation where two moves connect at the same time.",
	"TRADE" : "A situation where two moves connect at the same time.",
	"TRIP GUARD" : "The ability to block when landing from a jump.",
	"TURTLING" : "A type of playstyle that focuses on defense and blocking the opponent's attacks.",
	"TURTLE" : "A type of playstyle that focuses on defense and blocking the opponent's attacks.",
	// "UNBLOCKABLE" : "A type of attack that cannot be blocked.",
	"VORTEX" : "A situation where the opponent must guess between multiple options and, if incorrect, is put back into the same situation.",
	"WAKE-UP ATTACKS" : "An attack that is done while getting up off the ground after being knocked down.",
	"WAKE-UP ATTACK" : "An attack that is done while getting up off the ground after being knocked down.",
	"WAKEUP ATTACKS" : "An attack that is done while getting up off the ground after being knocked down.",
	"WAKEUP ATTACK" : "An attack that is done while getting up off the ground after being knocked down.",
	"WAKE-UPS" : "The moment a character is getting up off the ground after being knocked down.",
	"WAKE-UP" : "The moment a character is getting up off the ground after being knocked down.",
	"WAKEUPS" : "The moment a character is getting up off the ground after being knocked down.",
	"WAKEUP" : "The moment a character is getting up off the ground after being knocked down.",
	"WAVEDASHING" : "An advanced technique that allows a character to quickly move forward or backward through a combination of inputs, drastically increasing their mobility.",
	"WAVEDASHES" : "An advanced technique that allows a character to quickly move forward or backward through a combination of inputs, drastically increasing their mobility.",
	"WAVEDASH" : "An advanced technique that allows a character to quickly move forward or backward through a combination of inputs, drastically increasing their mobility.",
	"WHIFFING" : "An attack that completely misses the opponent.",
	"WHIFFED" : "An attack that completely misses the opponent.",
	"WHIFFS" : "An attack that completely misses the opponent.",
	"WHIFF" : "An attack that completely misses the opponent.",
	"ZONED" : "The ability to control space or “zones”. Projectiles are commonly used in zoning to keep the opponent from moving freely.",
	"ZONE" : "The ability to control space or “zones”. Projectiles are commonly used in zoning to keep the opponent from moving freely.",
	"ZONING" : "A type of playstyle that relies on controlling space or “zones”. Projectiles are commonly used in zoning to keep the opponent from moving freely."
}

// Mortal Kombat 11 Keywords & Definitions
var mk11_keywords = {

	"AIR ESCAPE" : "A defensive mechanic that allows a player to escape an aerial combo. During an Air Escape, the player gains armor on the way down. Requires 2 bars of Defensive Meter.",
	"AMPLIFYING" : "The ability to enhance a Special Move. Requires 1 bar of Offensive Meter.",
	"AMPLIFIED" : "The ability to enhance a Special Move. Requires 1 bar of Offensive Meter.",
	"AMPLIFIES" : "The ability to enhance a Special Move. Requires 1 bar of Offensive Meter.",
	"AMPLIFY" : "The ability to enhance a Special Move. Requires 1 bar of Offensive Meter.",
	"ARMOR BREAKING" : "The ability to destroy a character's armor.",
	"ARMOR BREAKS" : "The ability to destroy a character's armor.",
	"ARMOR BREAK" : "The ability to destroy a character's armor.",
	"ARMOR" : "A state that prevents a character from flinching when being hit.",
	"BREAKAWAYS" : "A defensive mechanic that allows a player to escape an aerial combo.", // During a Breakaway, the player gains armor on the way down. Requires 2 bars of Defensive Meter.",
	"BREAKAWAY" : "A defensive mechanic that allows a player to escape an aerial combo.", // During a Breakaway, the player gains armor on the way down. Requires 2 bars of Defensive Meter.",
	"DEFENSIVE METER" : "A meter that can be used for defensive-based moves.", // Defensive Meter recharges at a varying rate over time, depending on the move used. A player can have a maximum of 2 bars of Defensive Meter.",
	"DELAYED GETUPS" : "A type of Getup that allows a player to stay on the ground for a longer period of time after being knocked down.",
	"DELAYED GETUP" : "A type of Getup that allows a player to stay on the ground for a longer period of time after being knocked down.",
	"FATAL BLOWS" : "A powerful attack that can only be done when at 30% health or less.", // When using a Fatal Blow, the player gains armor during the attack. If a Fatal Blow is blocked or whiffs, there is a short cooldown period before it can be used again. After landing a successful a Fatal Blow, it cannot be used again for the remainder of the match.",
	"FATAL BLOW" : "A powerful attack that can only be done when at 30% health or less.", // When using a Fatal Blow, the player gains armor during the attack. If a Fatal Blow is blocked or whiffs, there is a short cooldown period before it can be used again. After landing a successful a Fatal Blow, it cannot be used again for the remainder of the match.",
	"FLAWLESS BLOCK ATTACKS" : "An attack that can be done after a successful Flawless Block.", // A player can perform either a quick armored attack that deals a small amount of damage or a slow anti-aerial attack that grants a combo on hit. Requires 1 bar of Offensive Meter and 1 bar of Defensive Meter.",
	"FLAWLESS BLOCK ATTACK" : "An attack that can be done after a successful Flawless Block.", // A player can perform either a quick armored attack that deals a small amount of damage or a slow anti-aerial attack that grants a combo on hit. Requires 1 bar of Offensive Meter and 1 bar of Defensive Meter.",
	"FLAWLESS BLOCKABLE" : "A special type of block that occurs when an attack is blocked within 3 frames upon contact.", // When a move is Flawless Blocked, the player takes reduced chip damage and may be at greater frame advantage. This can allow for certain moves to be punished that are normally safe on block.",
	"FLAWLESS BLOCKING" : "A special type of block that occurs when an attack is blocked within 3 frames upon contact.", // When a move is Flawless Blocked, the player takes reduced chip damage and may be at greater frame advantage. This can allow for certain moves to be punished that are normally safe on block.",
	"FLAWLESS BLOCKED" : "A special type of block that occurs when an attack is blocked within 3 frames upon contact.", // When a move is Flawless Blocked, the player takes reduced chip damage and may be at greater frame advantage. This can allow for certain moves to be punished that are normally safe on block.",
	"FLAWLESS BLOCKS" : "A special type of block that occurs when an attack is blocked within 3 frames upon contact.", // When a move is Flawless Blocked, the player takes reduced chip damage and may be at greater frame advantage. This can allow for certain moves to be punished that are normally safe on block.",
	"FLAWLESS BLOCK" : "A special type of block that occurs when an attack is blocked within 3 frames upon contact.", // When a move is Flawless Blocked, the player takes reduced chip damage and may be at greater frame advantage. This can allow for certain moves to be punished that are normally safe on block.",
	"GETUP ATTACKS" : "A type of Getup that allows a player to counterattack the opponent after being knocked down.", // A player can perform either a quick armored attack that deals a small amount of damage or a slow anti-aerial attack that grants a combo on hit. Requires 1 bar of Offensive Meter and 1 bar of Defensive Meter.",
	"GETUP ATTACK" : "A type of Getup that allows a player to counterattack the opponent after being knocked down.", // A player can perform either a quick armored attack that deals a small amount of damage or a slow anti-aerial attack that grants a combo on hit. Requires 1 bar of Offensive Meter and 1 bar of Defensive Meter.",
	"GETUPS" : "A defensive mechanic that allows a player to perform certain moves after being knocked down.", // There are 3 types of Getups: Delayed Getup, Getup Attack, and Roll Escape.",
	"GETUP" : "A defensive mechanic that allows a player to perform certain moves after being knocked down.", // There are 3 types of Getups: Delayed Getup, Getup Attack, and Roll Escape.",
	// "HOP ATTACKS" : "An aerial attack that can be done after a Hop. Hop Attacks hit as overheads on the way down, deal little damage and are usually unsafe on block.",
	// "HOP ATTACK" : "An aerial attack that can be done after a Hop. Hop Attacks hit as overheads on the way down, deal little damage and are usually unsafe on block.",
	// "HOPS" : "A type of jump that allows a player to hop slightly above the ground.",
	// "HOP" : "A type of jump that allows a player to hop slightly above the ground.",
	"INTERACTABLES" : "An object on the screen that can be used to assist in the fight.", // Interactables vary depending on the stage and can either be used offensively or defensively. Interactables can be Amplified, granting armor during use. Certain interactables also grant invincibility for a short period of time.",
	"INTERACTABLE" : "An object on the screen that can be used to assist in the fight.", // Interactables vary depending on the stage and can either be used offensively or defensively. Interactables can be Amplified, granting armor during use. Certain interactables also grant invincibility for a short period of time.",
	"KOUNTERS" : "An attack that is done while interrupting an opponent's attack.",
	"KOUNTER" : "An attack that is done while interrupting an opponent's attack.",
	"KRUSHING BLOWS" : "A special type of attack that can be performed after meeting certain requirements.", // These requirements generally depend on the move that's used. Krushing Blows deal a huge amount of damage, with some launching for a combo. Each Krushing Blow can only be used once per match.",
	"KRUSHING BLOW" : "A special type of attack that can be performed after meeting certain requirements.", // These requirements generally depend on the move that's used. Krushing Blows deal a huge amount of damage, with some launching for a combo. Each Krushing Blow can only be used once per match.",
	"OFFENSIVE METER" : "A meter that can be used for offensive-based moves.", // Offensive Meter recharges at a varying rate over time, depending on the move used. A player can have a maximum of 2 bars of Offensive Meter.",
	"REVERSALS" : "An attack that is done immediately after coming out of block.",
	"REVERSAL" : "An attack that is done immediately after coming out of block.",
	"ROLL ESCAPES" : "A type of Getup that allows a player to roll forward or away from the opponent after being knocked down.", // During a Roll Escape, the player gains armor. Requires 1 bar of Defensive Meter.",
	"ROLL ESCAPE" : "A type of Getup that allows a player to roll forward or away from the opponent after being knocked down.", // During a Roll Escape, the player gains armor. Requires 1 bar of Defensive Meter.",
	"THROW ESCAPES" : "A defensive mechanic that allows a player to prevent from being thrown.", // There is a short window that a Throw Escape can be used. The throw must also be teched in the correct direction that the opponent throws in.",
	"THROW ESCAPE" : "A defensive mechanic that allows a player to prevent from being thrown." // There is a short window that a Throw Escape can be used. The throw must also be teched in the correct direction that the opponent throws in."
}

// Regular Expression for Keywords and Ignores HTML Tags
var regEx = new RegExp("(" + Object.keys(keywords).join("|") + "|" + Object.keys(mk11_keywords).join("|") + ")(?!([^<]+)?>)", "gi");

// Check if Text Class Exists
var textClassPage = document.getElementsByClassName('single-post-content'); // Pages
var textClassPost = document.getElementsByClassName('entry-content'); // Posts

var text;

// Get Post Text
if (textClassPage.length > 0) { text = textClassPage[0].innerHTML; }
else if (textClassPost.length > 0) { text = textClassPost[0].innerHTML; }

if (text) {
	// Replace Post Text with Keywords
	var newText = text.replace(regEx, function(keyword) {
		var replace;

		// Check if Keyword is in Keyword Map, if not then uses Mortal Kombat 11 Keyword Map
		if (keyword.toUpperCase() in keywords) {
			var replace = '<span class="keyword">' + keyword + '<span class="definition">' + keywords[keyword.toUpperCase()] + '</span></span>';
		}
		else if (keyword.toUpperCase() in mk11_keywords) {
			var replace = '<span class="mk11_keyword">' + keyword + '<span class="definition">' + mk11_keywords[keyword.toUpperCase()] + '</span></span>';
		}

		return replace;
	});

	if (textClassPage.length > 0) { document.getElementsByClassName('single-post-content')[0].innerHTML = newText; }
	else if (textClassPost.length > 0) { document.getElementsByClassName('entry-content')[0].innerHTML = newText; }
}

// Add Touch Capability for Mobile Devices
document.body.setAttribute('ontouchstart', '');